# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wS9Z3Sf_VTGrixsCjseDTS1S0yT3j9DA

# Training dataset - Fondamenti di Pandas
"""

pip install pandas

import pandas as pd

from google.colab import files
file=files.upload()

from IPython.core.interactiveshell import default
df=pd.read_csv("Training_data.csv")
print(df)

df.index = range(1, len(df) + 1)

df.head(10) #visualizzo le prime 10 righe

df.columns #visualizzo nomi colonne

df.shape #quante righe e colonne ci sono nel dataset

df.dtypes #tipo di ogni colonna del df

df.isnull().sum() #check valori nulli

df['Date'] = df['Date'].fillna('2020-01-01') #gestione nan Date
print(df)

df['Calories'] = df['Calories'].fillna(df['Calories'].mean()) #media per assegnare un valore di default
print(df)

df[['Pulse','Calories']] #visualizzo solo le colonne Pulse e Calories

df.loc[1:14,['Date','Maxpulse']] #metodo loc

df.iloc[9:14,[1,2,4]] #metodo iloc